favicon: favicon.jpg

menu:
  首页: /
  标签: /tags/
  关于: /about/

copyright:
  name: AI Blog

twikoo:
  enable: false
  envId : 您的环境id
  region: ap-guangzhou
  lang: zh-CN

beaudar:
  enable: false
  repo : mouyase/Yojigen.Tech
  branch: main

friends:
  - name: GitHub
    url: https://github.com/MichaelSatoshi1983
